# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "https://jessesrodrigues.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : PET-Informática
logo       : /assets/img/logo_PET.png
email      : your-email@example.com #this is also the email contact forms will go to
description: "Novo site oficial do PET-Informática/PUCRS"
author     : Your Name
# logo:     #optional, defaults to site title
  # path: assets\img\clients\creative-market.jpg
  # height: 60 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme

gems:
  - jekyll-paginate-v2
  
pagination:
 enabled: true # Habilita a paginação
 per_page: 3 # Quantidade de postagens por página
 permalink: '/page:num/' # URL que será exibido ao navegar entre as página
 sort_reverse: true # Habilita a opção de voltar à página anterior
 sort_field: 'date' # Filtra a paginação de acordo com a data de publicação das postagens
 title: 'Página :num' # Nome de exibição que será carregado no <title> do blog
 trail:
   before: 2 # Exibe o número de postagens a esquerda
   after: 2 # Exibe o número de postagens a direita
